/**
 * Generates `__registry__/index.ts` from `registry/examples/*.tsx`.
 *
 * For each example we capture: a lazy import of the live component, the raw
 * source (for the copy button), and Shiki-highlighted HTML (dual light/dark
 * theme). Highlighting at build time keeps <ComponentPreview> a pure client
 * component with no runtime highlighter.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { codeToHtml } from 'shiki'

const here = dirname(fileURLToPath(import.meta.url))
const examplesDir = join(here, '..', 'registry', 'examples')
const outDir = join(here, '..', '__registry__')

const files = readdirSync(examplesDir)
  .filter((f) => f.endsWith('.tsx'))
  .sort()

const entries: { name: string; source: string; html: string }[] = []
for (const file of files) {
  const name = file.replace(/\.tsx$/, '')
  const source = readFileSync(join(examplesDir, file), 'utf8').trimEnd()
  // defaultColor: false → emit only `--shiki-light` / `--shiki-dark` CSS
  // variables (no inline color), so global.css applies each theme cleanly.
  const html = await codeToHtml(source, {
    lang: 'tsx',
    themes: { light: 'github-light', dark: 'github-dark' },
    defaultColor: false,
  })
  entries.push({ name, source, html })
}

const body = `// GENERATED by scripts/build-registry.ts — do not edit by hand.
import * as React from 'react'

export interface RegistryEntry {
  component: React.LazyExoticComponent<React.ComponentType>
  source: string
  html: string
}

export const Index: Record<string, RegistryEntry> = {
${entries
  .map(
    (e) =>
      `  ${JSON.stringify(e.name)}: {\n` +
      `    component: React.lazy(() => import(${JSON.stringify(`@/registry/examples/${e.name}`)})),\n` +
      `    source: ${JSON.stringify(e.source)},\n` +
      `    html: ${JSON.stringify(e.html)},\n` +
      `  },`,
  )
  .join('\n')}
}
`

mkdirSync(outDir, { recursive: true })
writeFileSync(join(outDir, 'index.ts'), body)
console.log(`registry: generated ${entries.length} examples`)
